apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: KUBE_CLUSTER_CERTIFICATE
    server: https://KUBE_ENDPOINT:KUBE_PORT
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: KUBE_USERNAME
    password: KUBE_ADMIN_PWD