apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "teknichrono"
    version: "${project.version}"
    group: "fabricepipart"
  name: "teknichrono"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: "teknichrono"
    version: "${project.version}"
    group: "fabricepipart"
  type: "ClusterIP"